# Bastion Gilded — kitty

foreground              #C5BFAF
background              #000000
selection_foreground    #E4DFD2
selection_background    #3A2C40

cursor                  #C57AD4
cursor_text_color       #000000

url_color               #C57AD4
active_border_color     #C57AD4
inactive_border_color   #1E1B16

active_tab_foreground   #E4DFD2
active_tab_background   #16130E
inactive_tab_foreground #6C6961
inactive_tab_background #000000

color0  #1A1A21
color1  #C68975
color2  #72A17E
color3  #E4C18C
color4  #9BAFCA
color5  #C5A44A
color6  #61A2A9
color7  #C5BFAF
color8  #6C6961
color9  #D98484
color10 #8EB998
color11 #F0D07C
color12 #86A6CE
color13 #C57AD4
color14 #7AB9C0
color15 #D6D1DE
