# Bastion Black Clear — kitty
# include this from kitty.conf:  include bastion-black.conf

foreground              #C2BDCB
background              #000000
selection_foreground    #E6E2EC
selection_background    #3A2C40

cursor                  #D497E0
cursor_text_color       #000000

url_color               #D497E0
active_border_color     #D497E0
inactive_border_color   #1A1A21

active_tab_foreground   #E6E2EC
active_tab_background   #141419
inactive_tab_foreground #807D88
inactive_tab_background #000000

color0  #1A1A21
color1  #CE8483
color2  #91B79A
color3  #DEC47F
color4  #89A4C5
color5  #C796D8
color6  #85B7BD
color7  #C2BDCB
color8  #807D88
color9  #E8A1A0
color10 #B0D3B8
color11 #FFE281
color12 #A4BEDF
color13 #D497E0
color14 #A0D3D9
color15 #E6E2EC
