# Bastion Cipher — kitty

foreground              #C2BEB6
background              #000000
selection_foreground    #000000
selection_background    #F5D47A

cursor                  #F5D47A
cursor_text_color       #000000

url_color               #F5D47A
active_border_color     #F5D47A
inactive_border_color   #1E1B14

active_tab_foreground   #000000
active_tab_background   #F5D47A
inactive_tab_foreground #6B6862
inactive_tab_background #000000

color0  #1A1A21
color1  #CD907B
color2  #72A17E
color3  #EACBA2
color4  #9CACBC
color5  #C0A766
color6  #61A2A9
color7  #C2BEB6
color8  #6B6862
color9  #D98484
color10 #8EB998
color11 #FBD980
color12 #86A6CE
color13 #F5D47A
color14 #7AB9C0
color15 #D6D1DE
