# Bastion Black Clear — foot
# in foot.ini:  include=~/.config/foot/bastion-black.ini

[cursor]
color=000000 d497e0

[colors]
foreground=c2bdcb
background=000000
selection-foreground=e6e2ec
selection-background=3a2c40

regular0=1a1a21
regular1=ce8483
regular2=91b79a
regular3=dec47f
regular4=89a4c5
regular5=c796d8
regular6=85b7bd
regular7=c2bdcb
bright0=807d88
bright1=e8a1a0
bright2=b0d3b8
bright3=ffe281
bright4=a4bedf
bright5=d497e0
bright6=a0d3d9
bright7=e6e2ec
