# Bastion Amber — kitty

foreground              #BCB5AD
background              #000000
selection_foreground    #000000
selection_background    #FCDA70

cursor                  #FCDA70
cursor_text_color       #000000

url_color               #FCDA70
active_border_color     #FCDA70
inactive_border_color   #1E1A13

active_tab_foreground   #000000
active_tab_background   #FCDA70
inactive_tab_foreground #807A72
inactive_tab_background #000000

color0  #4E4A44
color1  #D9897E
color2  #92AF82
color3  #ECB060
color4  #86A6C2
color5  #C88DA9
color6  #7AB3B6
color7  #C2BBB2
color8  #807A72
color9  #EBA297
color10 #A8C39A
color11 #FFCE87
color12 #9DBCD6
color13 #DBA5BE
color14 #94C8CB
color15 #DFD9D3
